version: "3.1"

services:
  laravel_php:
    build:
      context: './php'
      dockerfile: Dockerfile
    container_name: laravel_php
    working_dir: "/var/www"
    volumes:
      - ./:/var/www
    expose:
      - 9000
    links:
        - laravel_mysql:laravel_mysql
    environment:
      - PORT=3306
      - DB_HOST=laravel_mysql

  laravel_nginx:
    build:
      context: './nginx'
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    links:
      - laravel_php
    ports:
      - 7777:80
    expose:
      - 80

  laravel_mysql:
    build:
      context: './mysql'
    container_name: laravel_mysql
    volumes:
      - laravel_db:/var/lib/mysql
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    expose:
        - 3306

volumes:
  laravel_db:
